search_boxs = () => {
  let input = document.getElementById("search-box").value;
  console.log(input);
  input = input.toLowerCase();
  let x = document.getElementsByClassName("team-card");

  for (i = 0; i < x.length; i++) {
    if (!x[i].innerHTML.toLowerCase().includes(input)) {
      x[i].style.display = "none";
    } else {
      x[i].style.display = "";
    }
  }
};

const playersData = [
  {
    id: 0,
    playerName: "Hardik Pandya",
    from: "MI",
    price: "6.50 Cr",
    isPlaying: true,
    description: "All-rounder",
  },
  {
    id: 1,
    playerName: "Virat Kohli",
    from: "RCB",
    price: "8.00 Cr",
    isPlaying: true,
    description: "Batsman",
  },
  {
    id: 2,
    playerName: "Yuvraj Singh",
    from: "MI",
    price: "1.00 Cr",
    isPlaying: false,
    description: "Batsman",
  },
  {
    id: 3,
    playerName: "Chris Morris",
    from: "RR",
    price: "16.25 Cr",
    isPlaying: true,
    description: "All-rounder",
  },
  {
    id: 4,
    playerName: "Glenn Maxwell",
    from: "RCB",
    price: "14.25",
    isPlaying: true,
    description: "All-rounder",
  },
  {
    id: 5,
    playerName: "Rohit Sharma",
    from: "MI",
    price: "6.50 Cr",
    isPlaying: true,
    description: "BatsMan",
  },
  {
    id: 6,
    playerName: "Ishan Kishan",
    from: "MI",
    price: "2.50 Cr",
    isPlaying: true,
    description: "BatsMan",
  },
];

var teams = [
  {
    id: 1,
    Team: "Chennai Super Kings",
    from: "CSK",
    players: [
      "Suresh Raina",
      "MS Dhoni",
      "Narayan Jagadeesabn",
      "Ruturaj Gaikwad",
      "KM Asif, Karn Sharma",
      "Ambati Rayudu",
      "Deepak Chahar",
      "Faf du Plessis",
      "Shardul Thakur",
      "Mitchell Santner",
      "Dwayne Bravo",
      "Lungi Ngidi",
      "Sam Curran",
      "Ravindra Jadeja",
      "Imran Tahir",
      "Robin Uthappa",
      "Moeen Ali",
      "K Gowtham",
      "Cheteshwar Pujara",
      " M.Harisankar Reddy",
      "K.Bhagath Varma",
      "C Hari Nishaanth",
      "R Sai Kishore",
    ],
    topBatsman: "Faf du Plessis",
    topBowler: "Sam Curran",
    championship: 3,
  },
  {
    id: 2,
    Team: "Delhi Capitals",
    from: "DC",
    players: [
      "Shreyas Iyer",
      "Ajinkya Rahane",
      "Amit Mishra",
      "Avesh Khan",
      "Axar Patel",
      "Ishant Sharma",
      "Kagiso Rabada",
      "Prithvi Shaw",
      "Rishabh Pant",
      "Shikhar Dhawan",
      "Lalit Yadav",
      "Marcus Stoinis",
      "Shimron Hetmyer",
      "Chris Woakes",
      "Anrich Nortje",
      "Steve Smith",
      "Umesh Yadav",
      "Ripal Patel",
      "Lukman Hussain Meriwala",
      "M Siddharth",
      "Tom Curran",
      "Sam Billings",
      "Pravin Dubey",
      "Vishnu Vinod",
    ],
    topBatsman: "Shikhar Dhawan",
    topBowler: "Avesh Khan",
    championship: 1,
  },
  {
    id: 3,
    Team: "Mumbai Indians",
    from: "MI",
    players: [
      "Rohit Sharma",
      "Aditya Tare",
      "Anmolpreet Singh",
      "Anukul Roy",
      "Dhawal Kulkarni",
      "Hardik Pandya",
      "Ishan Kishan",
      "Jasprit Bumrah",
      "Jayant Yadav",
      "Kieron Pollard",
      "Krunal Pandya",
      "Quinton de Kock",
      "Rahul Chahar",
      "Suryakumar Yadav",
      "Chris Lynn",
      "Mohsin Khan",
      "Saurabh Tiwary",
      "Trent Boult",
      "Adam Milne",
      "Nathan Coulter-Nile",
      "Piyush Chawla",
      "James Neeshan",
      "Yudhvir Charak",
      "Marco Jansen",
      "Arjun Tendulkar",
    ],
    topBatsman: "Rohit Sharma",
    topBowler: "Rahul Chahar",
    championship: 5,
  },

  {
    id: 4,
    Team: "Sunrisers Hyderabad",
    from: "SRH",
    players: [
      "Kane Williamson",
      "David Warner",
      "Manish Pandey",
      "Virat Singh",
      "Priyam Garg",
      "Abdul Samad",
      "Bhuvneshwar Kumar",
      "Khaleel Ahmed",
      "Sandeep Sharma",
      "Siddharth Kaul",
      "T Natarajan",
      "Abhishek Sharma",
      "Shahbaz Nadeem",
      "Vijay Shankar",
      "Mohammad Nabi",
      "Rashid Khan",
      "Jonny Bairstow",
      "Wriddhiman Saha",
      "Shreevats Goswami",
      "Basil Thampi",
      "Jason Holder",
      "Jagadeesha Suchith",
      "Kedar Yadav",
      "Mujeeb ur Rahman",
      "Jason Roy",
    ],
    topBatsman: "Jonny Bairstow",
    topBowler: "Rashid Khan",
    championship: 1,
  },

  {
    id: 5,
    Team: "Punjab Kings",
    from: "KX1P",
    players: [
      "KL Rahul",
      "Chris Gayle",
      "Mayank Agarwal",
      "Nicholas Pooran",
      "Mandeep Singh",
      "Sarfaraz Khan",
      "Deepak Hooda",
      "Prabhsimran Singh",
      "Mohammed Shami",
      "Chris Jordan",
      "Darshan Nalkande",
      "Ravi Bishnoi",
      "Murugan Ashwin",
      "Arshdeep Singh",
      "Harpreet Brar",
      "Ishan Porel",
      "Dawid Malan",
      "Jhye Richardson",
      "Shahrukh Khan",
      "Riley Meredith",
      "Moises Henriques",
      "Jalaj Saxena",
      "Utkarsh Singh",
      "Fabian Allen",
      "Saurabh Kumar",
    ],
    topBatsman: "KL Rahul",
    topBowler: "Mohammed Shami",
    championship: 0,
  },

  {
    id: 6,
    Team: "Rajasthan Royals",
    from: "RR",
    players: [
      "Sanju Samson",
      "Ben Stokes",
      "Jofra Archer",
      "Jos Buttler",
      "Riyan Parag",
      "Shreyas Gopal",
      "Rahul Tewatia",
      "Mahipal Lomror",
      "Kartik Tyagi",
      "Jaydev Unadkat",
      "Mayank Markande",
      "Yashasvi Jaiswal",
      "Anuj Rawat",
      "David Miller",
      "Manan Vohra",
      "Shivam Dube",
      "Chris Morris",
      "Mustafizur Rahim",
      "Chetan Sakariya",
      "K.C. Cariappa",
      "Kuldip Yadav",
      "Akash Singh",
    ],
    topBatsman: "Sanju Samson",
    topBowler: "Chris Morris",
    championship: 1,
  },

  {
    id: 7,
    Team: "Kolkata Knight Riders",
    from: "KKR",
    players: [
      "Dinesh Karthik",
      "Andre Russell",
      "Kamlesh Nagarkoti",
      "Kuldeep Yadav",
      "Lockie Ferguson",
      "Nitish Rana",
      "Prasidh Krishna",
      "Gurkeerat Singh Mann",
      "Sandeep Warrier",
      "Shivam Mavi",
      "Shubman Gill",
      "Sunil Narine",
      "Eoin Morgan",
      "Pat Cummins",
      "Rahul Tripathi",
      "Varun Chakravarthy",
      "Pawan Negi",
      "Tim Seifert",
      "Shakib al Hasan",
      "Sheldon Jackson",
      "Vaibhav Arora",
      "Karun Nair",
      "Harbhajan Singh",
      "Ben Cutting",
      "Venkatesh Iyer",
    ],
    topBatsman: "Andre Russell",
    topBowler: "Pat Cummins",
    championship: 2,
  },

  {
    id: 8,
    Team: "Royal Challengers Banglore",
    from: "RCB",
    players: [
      "Virat Kohli",
      "AB de Villiers",
      "Yuzvendra Chahal",
      "Devdutt Padikkal",
      "Harshal Patel",
      "Daniel Sams",
      "Washington Sundar",
      "Mohammed Siraj",
      "Navdeep Saini",
      "Shahbaz Ahmed",
      "Pavan Deshpande",
      "Glenn Maxwell",
      "Sachin Baby",
      "Rajat Patidar",
      "Mohammed Azharuddeen",
      "Kyle Jamieson",
      "Dan Christian",
      "Suyesh Prabhudessai",
      "KS Bharat",
      "Finn Allen",
    ],
    topBatsman: "Glenn Maxwell",
    topBowler: "Harshal Patel",
    championship: 0,
  },
];

$(document).ready(() => {
  var linkId = window.location.search.split("=")[1];
  console.log(linkId);
  const data1 = linkId[0] - 1;
  const data2 = linkId[1];
  //   console.log(data);
  $(".name_play").html("Player Name: " + teams[data1].players[data2]);
  $(".play_name").html("Team Name: " + teams[data1].Team);

  $(".play_price").html("Price: " + Math.trunc(Math.random() * 10) + 1 + "CR");
  $(".play_role").html("Role: All-Rounder");
  $(".play_play").html("Playing Status: Playing");
});
